<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="VM-HLand-QA01" name="com.ssp.regression.insurer.testscripts.US_6527" tests="5" failures="2" timestamp="11 Apr 2019 06:42:25 GMT" time="894.394" errors="0">
  <testcase name="TC_6527_7612" time="63.681" classname="com.ssp.regression.insurer.testscripts.US_6527"/>
  <testcase name="TC_6527_7619" time="0.000" classname="com.ssp.regression.insurer.testscripts.US_6527"/>
  <testcase name="TC_6527_7617" time="433.791" classname="com.ssp.regression.insurer.testscripts.US_6527"/>
  <testcase name="TC_6527_7613" time="5.663" classname="com.ssp.regression.insurer.testscripts.US_6527">
    <failure type="java.lang.Exception" message="java.lang.Exception: java.lang.Exception: java.lang.ArrayIndexOutOfBoundsException: 8">
      <![CDATA[java.lang.Exception: java.lang.Exception: java.lang.Exception: java.lang.ArrayIndexOutOfBoundsException: 8
	at com.ssp.uxp_pages.GetTestData.getObjectXmlData(GetTestData.java:229)
	at com.ssp.support.BaseTest.testCaseSteps(BaseTest.java:79)
	at com.ssp.regression.insurer.testscripts.US_6527.TC_6527_7613(US_6527.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:73)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Exception: java.lang.Exception: java.lang.ArrayIndexOutOfBoundsException: 8
	at com.ssp.uxp_pages.GetTestData.printnote(GetTestData.java:328)
	at com.ssp.uxp_pages.GetTestData.getObjectXmlData(GetTestData.java:223)
	... 17 more
Caused by: java.lang.Exception: java.lang.ArrayIndexOutOfBoundsException: 8
	at com.ssp.uxp_pages.GetTestData.printnote(GetTestData.java:328)
	at com.ssp.uxp_pages.GetTestData.printnote(GetTestData.java:321)
	... 18 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 8
	at com.ssp.uxp_pages.ActionKeyword.validateOrderedListTextEquals(ActionKeyword.java:1666)
	at com.ssp.uxp_pages.ActionKeyword.performActionBasedOnFieldType(ActionKeyword.java:286)
	at com.ssp.uxp_pages.GetTestData.printnote(GetTestData.java:316)
	... 19 more
]]>
    </failure>
  </testcase> <!-- TC_6527_7613 -->
  <testcase name="TC_6527_7633" time="391.259" classname="com.ssp.regression.insurer.testscripts.US_6527"/>
</testsuite> <!-- com.ssp.regression.insurer.testscripts.US_6527 -->
